// Copyright 2026 Ryan Wong
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package engine

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/pulumi/pulumi/pkg/v3/resource/deploy"
	"github.com/pulumi/pulumi/pkg/v3/resource/stack"
	"github.com/pulumi/pulumi/sdk/v3/go/common/apitype"
	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/config"
)

// Update plans.
//
// A plan is the set of operations a preview proposed, in the CLI's plan file
// format (apitype.DeploymentPlanV1, what `pulumi preview --save-plan` writes
// and `pulumi up --plan` reads). Secret property values in a plan are
// encrypted with the stack's secrets provider unless the preview ran with
// ShowSecrets, exactly as the CLI does, so a plan written by the library is
// readable by the CLI for the same stack and vice versa.
//
// Preview generates a plan when Options.SavePlan (a path) or
// Options.GeneratePlan (Result.Plan) is set. Up is constrained by a plan
// given as Options.Plan (a path) or Options.PlanJSON (the file's content).
// The engine then refuses any operation the plan did not propose (a
// replacement where an update was planned, an update where a same was
// planned, a resource the plan does not know) and fails the update with a
// PlanViolation naming the offending resources.

// PlanViolationResource is one resource whose operation exceeded the plan.
type PlanViolationResource struct {
	URN     string `json:"urn"`
	Message string `json:"message"`
}

// PlanViolation reports that an update constrained by a plan (Options.Plan or
// Options.PlanJSON) tried to perform operations the plan did not propose. The
// update stops at the first violating resource, as `pulumi up --plan` does;
// Resources lists every violation the engine reported.
type PlanViolation struct {
	Resources []PlanViolationResource
}

func (e PlanViolation) Error() string {
	if len(e.Resources) == 0 {
		return "update violates the plan"
	}
	parts := make([]string, 0, len(e.Resources))
	for _, r := range e.Resources {
		parts = append(parts, fmt.Sprintf("%s: %s", r.URN, strings.TrimSpace(r.Message)))
	}
	return "update violates the plan: " + strings.Join(parts, "; ")
}

// validatePlanOptions checks that the plan options match the operation kind.
func validatePlanOptions(kind Kind, opts Options) error {
	if kind != KindPreview && (opts.SavePlan != "" || opts.GeneratePlan) {
		return InvalidSpec{Field: "options.savePlan", Message: "plans are generated by Preview only"}
	}
	if kind != KindUp && (opts.Plan != "" || len(opts.PlanJSON) > 0) {
		return InvalidSpec{Field: "options.plan", Message: "a plan constrains Up only"}
	}
	if opts.Plan != "" && len(opts.PlanJSON) > 0 {
		return InvalidSpec{Field: "options.plan", Message: "set either plan (a path) or planJson, not both"}
	}
	return nil
}

// loadPlan reads the plan an Up is constrained by, from Options.Plan or
// Options.PlanJSON, decrypting secrets with the stack's decrypter.
func loadPlan(opts Options, dec config.Decrypter) (*deploy.Plan, error) {
	raw := []byte(opts.PlanJSON)
	if opts.Plan != "" {
		b, err := os.ReadFile(opts.Plan)
		if err != nil {
			return nil, InvalidSpec{Field: "options.plan", Message: err.Error()}
		}
		raw = b
	}
	if len(bytes.TrimSpace(raw)) == 0 {
		return nil, nil
	}
	var wire apitype.DeploymentPlanV1
	if err := json.Unmarshal(raw, &wire); err != nil {
		return nil, InvalidSpec{Field: "options.plan", Message: "not a plan file: " + err.Error()}
	}
	plan, err := stack.DeserializePlan(wire, dec)
	if err != nil {
		return nil, InvalidSpec{Field: "options.plan", Message: "deserializing plan: " + err.Error()}
	}
	return plan, nil
}

// encodePlan serialises a generated plan the way the CLI's plan.Write does
// (four-space indent, HTML escaping off), so Result.Plan and a SavePlan file
// are byte for byte what `pulumi preview --save-plan` writes.
func encodePlan(plan *deploy.Plan, enc config.Encrypter, showSecrets bool) ([]byte, error) {
	wire, err := stack.SerializePlan(plan, enc, showSecrets)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	e := json.NewEncoder(&buf)
	e.SetEscapeHTML(false)
	e.SetIndent("", "    ")
	if err := e.Encode(wire); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// isPlanViolationDiag recognises the engine's plan constraint errors
// (pkg/resource/deploy/step_generator.go validateSteps/generateSteps and
// deployment_executor.go's end-of-run check). They arrive as error
// diagnostics with the resource's URN.
func isPlanViolationDiag(msg string) bool {
	return strings.Contains(msg, "violates plan") ||
		strings.Contains(msg, "is not allowed by the plan") ||
		strings.Contains(msg, "expected resource operations for")
}

// planViolations collects the violations seen on the event stream. Caller
// holds o.mu.
func (o *Operation) planViolations() []PlanViolationResource {
	var out []PlanViolationResource
	for urn, msgs := range o.urnDiags {
		for _, m := range msgs {
			if isPlanViolationDiag(m) {
				out = append(out, PlanViolationResource{URN: urn, Message: strings.TrimSpace(m)})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].URN < out[j].URN })
	return out
}
